kind: pipeline
name: api
steps:
  - name: start
    commands:
      - echo '-----start------'
      - ls

  - name: build
    image: node:16
    depends_on: [clone]
    commands:
      - npm install --registry https://registry.npm.taobao.org
      - npm run build

  - name: end
    commands:
      - echo '-----end------'
      - ls
trigger:
  branch:
    - feat-hello
  event:
    - pull_request
    - push
