kind: pipeline
name: cola_ci
type: exec

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    depends_on: [clone]
    commands:
      - echo '-----start------'
      - ls
      - node -v
      - npm install --registry https://registry.npm.taobao.org
      - npm run build
      - echo '-----end------'
      - ls

  - name: deploy
    depends_on: [build]
    commands:
      - rm -rf /cola/cola_fe/*
      - cp -r dist/* /cola/cola_fe

trigger:
  branch:
    - feat-hello
  event:
    - pull_request
    - push
