kind: pipeline
name: cola_ci
type: docker

clone:
  disable: true

steps:
  - name: start
    commands:
      - echo '-----start------'
      - ls

trigger:
  branch:
    - feat-hello
  event:
    - pull_request
    - push
