kind: pipeline
name: cola_ci
type: docker

clone:
  disable: true

steps:
  - name: build
    image: node:16
    commands:
      - echo '-----start------'
      - ls
      - npm install --registry https://registry.npm.taobao.org
      - npm run build
      - echo '-----end------'
      - ls

trigger:
  branch:
    - feat-hello
  event:
    - pull_request
    - push
